### ISSUE TITLE
Ranks and Joined Date not exporting anymore

### ISSUE THREAD

**Issue by JoRouss** [fatfingers23/runelite-osrs-clanmate-export#3]
I get the Successful export message, but the Ranks and Joined Date are not exported along with the names anymore.

![image](https://user-images.githubusercontent.com/17717723/143961610-79f299a6-feef-420e-9a38-83183cbcdd5b.png)

I get a list of names, with blank rank and date.
Name1,,
Name2,,
[...]

**Comment by lukaschristensson** [comment]
I had this problem too. Here's solution for the setClanInfo function in src/main/java/com/clanmate_export/ClanMateExportPlugin.java . It works as far as I've tested it.

```
     /**
     * Sets clan info
     */
    private void setClanInfo() {
        //Gets and sets clan count
        Widget tab = this.client.getWidget(701, 1);
        if (tab == null || tab.getChildren() == null || tab.getChildren().length < 3) return;
        Widget memberCounterWidget = tab.getChild(2);
        if (memberCounterWidget != null) {
            if (memberCounterWidget.getText() != null) {
                String clanSizeText = Text.removeTags(memberCounterWidget.getText());
                try {
                    this.clanMemberCount = Integer.parseInt(clanSizeText);
                } catch (Exception e) {
                }
            }
        }
        //Gets and sets clan name
        Widget clanNameWidget = tab.getChild(0);
        if (clanNameWidget != null) {
            this.clanName = Text.removeTags(clanNameWidget.getText());
        }
    }
```

**Comment by fatfingers23** [comment]
Sorry about that everyone! I actually did not see these till tonight! Thank you @lukaschristensson for your troubleshooting! I was able to go directly in and fix the bug. This was my very first RL plugin and bit of java code. I found that the RL team had implemented some methods for the info I was needing. So I decided just to use them. Thanks again! 


Glad to see the plugin get some use! Going do a couple of other clean up items and submit the change.

**Comment by mmcmd** [comment]
Still getting this issue

**Comment by jndizoglio** [comment]
Thanks for updating this plugin, I am a co-owner of (full) Ironman clan and we use this plugin, combined with a custom made excel sheet to determine what members to kick to make room for new members based on rank, date joined and inactivity (pulled from temple osrs) and it being down for a few weeks was hurting that process. We appreciate your time to develop and upkeep this project! -Irons Tavern
