### ISSUE TITLE
Only RSN gets exported, not the rank

### ISSUE THREAD

**Issue by ste-h** [fatfingers23/runelite-osrs-clanmate-export#4]
https://i.imgur.com/V3syuDE.png

This is the export the plugin gives when exporting to clipboard, used it in the same way previously and it worked fine

**Comment by fatfingers23** [comment]
Hey, thank you for raising the issue! There has been a patch made for this and submitted to the plugin repository. Just waiting on the Runelite team to approve and merge.

https://github.com/runelite/plugin-hub/pull/2207

**Comment by fatfingers23** [comment]
Pr was accepted! Should be good to go now. Probably wait 15mins-30mins for it to push to their servers. Then restart Runeltie.
