### ISSUE TITLE
Issue exporting clan titles and join date

### ISSUE THREAD

**Issue by mmcmd** [fatfingers23/runelite-osrs-clanmate-export#5]
Sorry about that everyone! I actually did not see these till tonight! Thank you @lukaschristensson for your troubleshooting! I was able to go directly in and fix the bug. This was my very first RL plugin and bit of java code. I found that the RL team had implemented some methods for the info I was needing. So I decided just to use them. Thanks again! 

Glad to see the plugin get some use! Going do a couple of other clean up items and submit the change.

_Originally posted by @fatfingers23 in https://github.com/fatfingers23/runelite-osrs-clanmate-export/issues/3#issuecomment-997157008_

Unfortunately this issue seems to be back

**Comment by fatfingers23** [comment]
I am not able to recreate the issue again. Make sure inside of Plugin-Hub that your version matches the same as in the picture. If that does not work, feel free to post a picture of the settings and an export example format, and I'll see what I can do. 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/20476157/147707144-8580cad2-33cb-4c3a-879c-0de0b3a750f0.png">

**Comment by mmcmd** [comment]
Thanks, it works now
